### ISSUE TITLE
Add support for using docker network

### ISSUE THREAD

**Issue by Toomblr** [almeidapaulopt/tsdproxy#18]
Hi!

First of all: great initiative, I've been searching for this kind of a solution for quite a while!

I have an idea / enhancement. I'd like to use docker network instead of exposing ports on the host. This is how I use my reverse proxy NPM (Nginx Proxy Manager). All my containers I'd like to expose to the proxy are in the same docker network together with the proxy container, without exposing ports on the host itself. And in the proxy I still use `containername`:`port`

However, when I try this with TailscaleDockerProxy. I just get white pages when visiting the Tailscale address.

**Comment by NickBootOne** [comment]
love to see this.
Only have a few containers running with the host IP, the rest are al on a separate Docker Bridge VLAN (in my case Br0.30).

The ones that are in Host mode are working fine with the Proxy, the ones that have the Docker Bridge VLAN are not

**Comment by noahkiss** [comment]
Nick, what happens if you run a second instance of this container on the same bridge network? Maybe that would work to register those containers?

**Comment by noahkiss** [comment]
@Toomblr I've just tested on a container which doesn't have any exposed ports. As long as I set a label on that container with the correct `container_port`, I don't need to have the port exposed and I can still access it via the machine which is created. 

I tested this with the Big-AGI container, which serves on port 3000. I don't have any port mappings. I set `tsdproxy.enable=true` and `tsdproxy.container_port=3000`. I can then access the container via `https://big-agi.funny-name.ts.net[:443]` in my browser. Does this sound like what you're trying to do? Note that I don't believe the port is mapped directly in this instance (I can't access at `big-agi.funny-name.ts.net:3000`), it will be proxied to `443`.

**Comment by noahkiss** [comment]
None of this solves the problem, but is hopefully a way to explain what exactly is happening.

```docker-compose
# https://tailscale.com/blog/docker-tailscale-guide

services:
  ts-webserver1:
    image: tailscale/tailscale:latest
    hostname: webserver1
    environment:
      - TS_AUTHKEY=tskey-auth-k7TsXC6CNTRL-D9notarealAuthKey2NFQQcUvtP9WJ
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-data-webserver1:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  webserver1:
      image: nginx
      network_mode: service:ts-webserver1
      depends_on: 
        - ts-webserver1
```

where Tailscale then registers a machine called `webserver1` and you can then access any ports that the `nginx` image has exposed (maybe nginx isn't the best example here, imagine something like radarr on 7878, for instance, and then accessing it via `webserver1:7878`)

I don't understand too much about how the networking is handled here, but here's the mental model I've come up with to compare these two:

With the above example, the Tailscale sidecar container is effectively creating a machine that the nginx image will run on, similar to a macvlan where the container would get its own IP. Then any other containers using the same network are implicitly available without publishing the ports (how? I don't know. Maybe similar to socat, [discussed here](https://se7entyse7en.dev/posts/accessing-an-unpublished-port-of-a-running-docker-container/).).

With TsDProxy, the TsDProxy container currently doesn't "slide in" to the target container's network, nor does it host its own network that the target container uses (so it's not creating a machine like the previous example, rather just a proxy). Because of this, TsDProxy needs the target container to have published the port. Now, this can even be accomplished using ephemeral publishing, i.e. not explicitly mapping the external port (think `-p 7878` instead of `-p 7878:7878`), and then, weirdly, TsDProxy still uses the *internal* port, even if the internal port is published to an external port that is different (`-p 7878:9000` TsDProxy will slide into the container and use `7878` directly, not just proxy connections to `docker_host:9000`).

**Comment by Korveck14** [comment]
I would also like to have this to avoid having to expose the ports when tsdproxy and all the services are just in the same docker network bridge, so you can access to them using the container name + port like `overseer:5050`.

**Comment by NickBootOne** [comment]
> Nick, what happens if you run a second instance of this container on the same bridge network? Maybe that would work to register those containers?

That also didn't work for the Containers that where connected through the VLAN Bridge
Only for the Host IP

**Comment by simonhammes** [comment]
I would also like to see this.

In fact, it already works _for a single service_ if you add both `tsdproxy` and your service to the same network and set the value of `TSDPROXY_HOSTNAME` to the service name.

My guess is that `getTargetHostname()` needs to be modified to check if tsdproxy can resolve the service name and use it if this is the case:

https://github.com/almeidapaulopt/tsdproxy/blob/92674fc3c8e7421d9fc3e8ac131f4423ebdbc381/internal/containers/containers.go#L91-L109

**Comment by simonhammes** [comment]
I think I have a working solution. I'll push a PR later today.

Explicitly specifying the network name seems like the best approach since the service might be part of multiple Docker networks (e.g. to access a database or other services).

This is similar to how [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy?tab=readme-ov-file#basic-usage-example-using-docker-compose) solves this use-case.

**Comment by simonhammes** [comment]
I've opened a PR: https://github.com/almeidapaulopt/tsdproxy/pull/32

Feel free to give this a try. I'd like to hear your thoughts. I've also included some testing instructions in the PR description.

**Comment by almeidapaulopt** [comment]
V1.0.0 already uses internal ports. Have you tested it already?

**Comment by Toomblr** [comment]
Yes, it works. Thanks a lot for the effort!
